import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { generateHomePageSubheading } from '../../services/geminiService';

const FeatureCard: React.FC<{ title: string; description: string; icon: string }> = ({ title, description, icon }) => (
  <div className="bg-white dark:bg-dark-card rounded-lg shadow-lg p-6 text-center transform hover:scale-105 transition-transform duration-300">
    <div className="text-5xl mb-4 text-accent-blue">{icon}</div>
    <h3 className="text-xl font-bold mb-2 text-gray-900 dark:text-white">{title}</h3>
    <p className="text-gray-600 dark:text-gray-300">{description}</p>
  </div>
);

const HomePage: React.FC = () => {
  const [subheading, setSubheading] = useState('Loading your inspiration...');

  useEffect(() => {
    const fetchSubheading = async () => {
      const generatedSubheading = await generateHomePageSubheading();
      setSubheading(generatedSubheading);
    };
    fetchSubheading();
  }, []);

  return (
    <div>
      {/* Hero Section */}
      <section className="relative bg-gray-100 dark:bg-dark-bg text-center py-20 md:py-32 overflow-hidden">
        <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: "url('https://picsum.photos/1600/900?grayscale&blur=2')", opacity: 0.1 }}></div>
        <div className="relative z-10 max-w-4xl mx-auto px-4">
          <h1 className="text-4xl md:text-6xl font-extrabold text-gray-900 dark:text-white mb-4">
            Your AI Personal Trainer
          </h1>
          <p className="text-lg md:text-xl text-gray-600 dark:text-gray-300 mb-8 min-h-[28px]">
            {subheading}
          </p>
          <Link
            to="/workout"
            className="inline-block bg-accent-blue hover:bg-blue-700 text-white font-bold py-3 px-8 rounded-full text-lg transition-transform transform hover:scale-105"
            aria-label="Start your workout"
          >
            Start Workout
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-gray-50 dark:bg-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-extrabold text-gray-900 dark:text-white">Powered by AI</h2>
            <p className="mt-4 text-lg text-gray-600 dark:text-gray-400">Smart features to elevate your home workouts.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <FeatureCard
              title="Real-time Pose Correction"
              description="Our AI analyzes your form to provide instant feedback, helping you perform exercises correctly and avoid injuries."
              icon="🤸"
            />
            <FeatureCard
              title="Personalized Workout Plans"
              description="Get workout plans tailored to your goals, experience, and availability, generated by our advanced language model."
              icon="🤖"
            />
            <FeatureCard
              title="Intelligent Progress Tracking"
              description="Automatically track your reps, sets, and progress over time. Visualize your journey and stay motivated."
              icon="📈"
            />
          </div>
        </div>
      </section>
    </div>
  );
};

export default HomePage;
